# Generated by Django 3.1 on 2020-10-28 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processing_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to=processing_app.models.update_filename)),
                ('image_clahe', models.ImageField(upload_to=processing_app.models.update_filename)),
                ('image_axes', models.ImageField(upload_to=processing_app.models.update_filename)),
                ('image_contours', models.ImageField(upload_to=processing_app.models.update_filename)),
                ('image_illumination_removed', models.ImageField(upload_to=processing_app.models.update_filename)),
                ('white_color', models.FloatField(blank=True, default=-1, null=True)),
                ('red_color', models.FloatField(blank=True, default=-1, null=True)),
                ('light_brown_color', models.FloatField(blank=True, default=-1, null=True)),
                ('dark_brown_color', models.FloatField(blank=True, default=-1, null=True)),
                ('blue_gray_color', models.FloatField(blank=True, default=-1, null=True)),
                ('black_color', models.FloatField(blank=True, default=-1, null=True)),
                ('user_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
