# Generated by Django 3.1 on 2020-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproc',
            name='black_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='blue_gray_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='dark_brown_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='light_brown_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='red_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='white_color',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
