# Generated by Django 3.1 on 2020-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='a_b_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='a_p_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='area_c_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='area_p_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='b_b_a_b_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='b_b_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='b_p_a_p_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='b_p_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='circularity_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='description',
            field=models.TextField(blank=True, default='brak opisu', max_length=300),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='entropy_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='equivalent_diameter_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='extent_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='p_p_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='patient_name',
            field=models.CharField(blank=True, default='brak', max_length=30),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='solidity_feature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='black_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='blue_gray_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='dark_brown_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='light_brown_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='red_color',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='white_color',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
