# Generated by Django 3.1 on 2020-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0002_auto_20201028_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='description',
            field=models.CharField(blank=True, default='brak opisu', max_length=300),
        ),
        migrations.AddField(
            model_name='imageproc',
            name='patient_name',
            field=models.CharField(blank=True, default='brak', max_length=30),
        ),
    ]
