# Generated by Django 3.1 on 2020-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0003_auto_20201028_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproc',
            name='description',
            field=models.TextField(blank=True, default='brak opisu', max_length=300),
        ),
    ]
