# Generated by Django 3.1 on 2020-10-15 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
