# Generated by Django 3.1 on 2020-10-16 08:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='name',
        ),
        migrations.AddField(
            model_name='examination',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='examination',
            name='diagnose',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='user_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
