# Generated by Django 3.1 on 2020-11-04 07:38

import classification_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0002_auto_20201016_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='image',
            field=models.ImageField(upload_to=classification_app.models.update_filename),
        ),
    ]
